dist: trusty

language: node_js

sudo: required

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

cache:
  directories:
    - node_modules

notifications:
  email: false

node_js:
  - "6"
  - "8"
  - "lts/*"

before_script:
  - npm prune
after_script: "npm install coveralls@2 && cat ./coverage/report-lcov/lcov.info | coveralls"

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
