language: node_js

sudo: required

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

cache:
  directories:
    - node_modules

notifications:
  email: false

node_js:
  - '7'
  - '6'

before_script:
  - npm prune

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
